
[window]

dimensions = { columns = 80, lines = 25}
padding = { x = 16, y = 16 }
opacity = 0.8

[font]
normal = { family = "Iosevka", style = "Regular"}
size = 16

[colors]

[colors.primary]
foreground = "#d4d4d4"
background = "#121212"

[colors.normal]
red     = "#fdb2d4"
yellow  = "#f8e9a6"
green   = "#cdf6a0"
cyan    = "#aaeaf6"
blue    = "#98c4f3"
magenta = "#c4a9f8"

[colors.bright]
red     = "#fdb2d4"
yellow  = "#f8e9a6"
green   = "#cdf6a0"
cyan    = "#aaeaf6"
blue    = "#98c4f3"
magenta = "#c4a9f8"

[cursor]
style = { shape = "underline", blinking = "On" }

[keyboard]
bindings = [
    { key ="c", mods = "Control", mode = "AppCursor", action = "Copy" },
    { key ="v", mods = "Control", mode = "AppCursor", action = "Paste" },
]

